export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const LOAD_ONE_USER = "LOAD_ONE_USER";
export const LOAD_ALL_USERS = "LOAD_ALL_USERS";